# https://github.com/travis-ci/travis-ci/issues/649
# https://github.com/exKAZUu/TravisTemplateForCSharpMono/blob/master/.travis.yml
language: objective-c

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby-head

jdk:
  - oraclejdk8

env:
  - TARGET_LANG=csharp MONO_VERSION="3.2.7" DMG=0
  - TARGET_LANG=csharp MONO_VERSION="3.0.12" DMG=1
  - TARGET_LANG=java MONO_VERSION="3.2.7" DMG=0
  - TARGET_LANG=ruby MONO_VERSION="3.2.7" DMG=0
  - TARGET_LANG=javascript MONO_VERSION="3.2.7" DMG=0

matrix:
  exclude:
    - env: TARGET_LANG=csharp MONO_VERSION="3.2.7" DMG=0
      rvm: 2.0.0
    - env: TARGET_LANG=csharp MONO_VERSION="3.2.7" DMG=0
      rvm: 2.1.0
    - env: TARGET_LANG=csharp MONO_VERSION="3.2.7" DMG=0
      rvm: jruby-head
    - env: TARGET_LANG=csharp MONO_VERSION="3.0.12" DMG=1
      rvm: 2.0.0
    - env: TARGET_LANG=csharp MONO_VERSION="3.0.12" DMG=1
      rvm: 2.1.0
    - env: TARGET_LANG=csharp MONO_VERSION="3.0.12" DMG=1
      rvm: jruby-head
    - env: TARGET_LANG=java MONO_VERSION="3.2.7" DMG=0
      rvm: 2.0.0
    - env: TARGET_LANG=java MONO_VERSION="3.2.7" DMG=0
      rvm: 2.1.0
    - env: TARGET_LANG=java MONO_VERSION="3.2.7" DMG=0
      rvm: jruby-head
    - env: TARGET_LANG=javascript MONO_VERSION="3.2.7" DMG=0
      rvm: 2.0.0
    - env: TARGET_LANG=javascript MONO_VERSION="3.2.7" DMG=0
      rvm: 2.1.0
    - env: TARGET_LANG=javascript MONO_VERSION="3.2.7" DMG=0
      rvm: jruby-head

before_install:
  - export EnableNuGetPackageRestore=true
  - "if [ \"$TARGET_LANG\" = \"ruby\" ]; then gem update bundler; fi"
  - "if [ \"$DMG\" = \"0\" ]; then wget \"http://download.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg\"; fi"
  - "if [ \"$DMG\" = \"0\" ]; then sudo installer -pkg \"MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg\" -target /; fi"
  - "if [ \"$DMG\" = \"1\" ]; then wget \"http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.dmg\"; fi"
  - "if [ \"$DMG\" = \"1\" ]; then hdid \"MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.dmg\"; fi"
  - "if [ \"$DMG\" = \"1\" ]; then sudo installer -pkg \"/Volumes/Mono Framework MDK ${MONO_VERSION}/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg\" -target /; fi"
  # https://github.com/travis-ci/travis-ci/issues/2839
  - export JAVA_HOME="$(/usr/libexec/java_home)"
  # install jq
  - brew install jq

script: "cd $TARGET_LANG; make"

branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  irc:
    - "irc.freenode.org#cucumber"
